// App Colors - semantic aliases for Figma colors
export {
  whiteColor,
  blackColor,
  appBackgroundColor,
  appFontColor,
  textColor,
  textColorMedium,
  textColorLight,
  primaryColor,
  primaryHoverColor,
  primaryActiveColor,
  gradientBlueStart,
  gradientBlueEnd,
  secondaryColor,
  secondaryHoverColor,
  secondaryActiveColor,
  primaryLightColor,
  primaryLightHoverColor,
  primaryLightActiveColor,
  softGreenColor,
  softBlueColor,
  softRedColor,
  softYellowColor,
  inputBackgroundColor,
  inputBackgroundHoverColor,
  inputBorderColor,
  menuItemColor,
  menuISubtemColor,
  appTextColor,
} from './constants';
